[project]
name = "langgraph-cognee"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cognee",
    "langchain",
    "langchain_openai",
    "langgraph",
    "python-dotenv",
]
